### ISSUE TITLE
Unhandled exception with v84

### ISSUE THREAD

**Issue by AndersHogqvist** [Holdi601/JoystickProfiler#51]
v83 works fine, but with v84 I get:

```
System.UnhandledExceptionEventArgs #
System.IO.IOException: The process cannot access the file 'F:\JoystickProfiler\log' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at System.IO.File.InternalAppendAllText(String path, String contents, Encoding encoding)
   at JoyPro.MainStructure.Write(String msg) in D:\Dropbox\Programmierung\c#\JoyPro\JoystickProfiler\JoyPro\JoyPro\General\MainStructure.cs:line 138
   at JoyPro.MainStructure.NoteError(Exception e) in D:\Dropbox\Programmierung\c#\JoyPro\JoystickProfiler\JoyPro\JoyPro\General\MainStructure.cs:line 128
   at JoyPro.OverlayBackGroundWorker.StartDCSListener() in D:\Dropbox\Programmierung\c#\JoyPro\JoystickProfiler\JoyPro\JoyPro\MISC\OverlayBackGroundWorker.cs:line 115
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```
And the log says:
```
[2022-11-08 15:45:03]: 	Startup Args:
[2022-11-08 15:45:03]: 	End of Args
[2022-11-08 15:45:03]: 	Program Started
[2022-11-08 15:45:03]: 	Setup UI Lists
[2022-11-08 15:45:03]: 	Crash catcher Setup
[2022-11-08 15:45:03]: 	Init WPF components
[2022-11-08 15:45:03]: 	Set def Height width
[2022-11-08 15:45:03]: 	Lookup this version
[2022-11-08 15:45:03]: 	Grid Borders light gray
[2022-11-08 15:45:03]: 	Buttons into list
[2022-11-08 15:45:03]: 	Setup Event Handlers
[2022-11-08 15:45:03]: 	First Start Init process
[2022-11-08 15:45:03]: 	InitProgram
[2022-11-08 15:45:03]: 	Check Newer Version
[2022-11-08 15:45:03]: 	Adding DCS to games
[2022-11-08 15:45:03]: 	Adding IL2 to games
[2022-11-08 15:45:03]: 	Adding SC to games
[2022-11-08 15:45:03]: 	GET DCS User Fodlers
[2022-11-08 15:45:03]: 	Backup User DCS config: C:\Users\ander\Saved Games\DCS
[2022-11-08 15:45:03]: 	Backup User DCS config: C:\Users\ander\Saved Games\DCS Updater Utility
[2022-11-08 15:45:03]: 	Backup User DCS config: C:\Users\ander\Saved Games\DCS.openbeta
[2022-11-08 15:45:03]: 	Start Other Threads
[2022-11-08 15:45:03]: 	Load IL2 Path
[2022-11-08 15:45:03]: 	Load SC Path
[2022-11-08 15:45:03]: 	Backup IL2
[2022-11-08 15:45:03]: 	Backup SC
[2022-11-08 15:45:03]: 	Load last meta
[2022-11-08 15:45:03]: 	NEWFILE TRUE
[2022-11-08 15:45:03]: 	F:\JoystickProfiler
[2022-11-08 15:45:03]: 	Load default DCS Inputs
[2022-11-08 15:45:03]: 	Load default DCS: F:\JoystickProfiler\CleanProfile\DCS\a-10a.cf
[2022-11-08 15:45:03]: 	Load default DCS: F:\JoystickProfiler\CleanProfile\DCS\A-10C II.cf
[2022-11-08 15:45:03]: 	Load default DCS: F:\JoystickProfiler\CleanProfile\DCS\A-10C II_easy.cf
[2022-11-08 15:45:05]: 	Load default DCS: F:\JoystickProfiler\CleanProfile\DCS\A-10C.cf
```

**Comment by Holdi601** [comment]
will fix today.

**Comment by Holdi601** [comment]
fixed now with v85
